---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Show info about groups this host belongs to
  debug:
    msg: "This host is in groups: {{ group_names | join(', ') }}."

- name: Provide repository apt key
  apt_key:
    url: "{{ key_url }}"
    state: present

- name: Add repository
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
    update_cache: yes
    filename: "mongodb-org-{{ mongodb_version }}"

- name: Install package
  apt:
    name: "{{ packages }}"
    state: present

- name: Change mongo config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongod

- name: Start mongod service on boot
  systemd:
    name: mongod
    enabled: yes
