---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Show info about groups this host belongs to
  debug:
    msg: "This host is in groups: {{ group_names | join(', ') }}."

- import_tasks: ruby.yml
- import_tasks: puma.yml
